name: pulse_storage_android

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/pulse_storage_android.yaml"
      - "pulse_storage_android/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/pulse_storage_android.yaml"
      - "pulse_storage_android/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.7.0
      working_directory: pulse_storage_android

