name: pulse_auth_ios
description: iOS implementation of the pulse_auth plugin
version: 1.0.0
homepage: https://pub.dev/

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: pulse_auth
    platforms:
      ios:
        pluginClass: PulseAuthPlugin
        dartPluginClass: PulseAuthIOS

dependencies:
  flutter:
    sdk: flutter
  pulse_auth_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^4.0.0
