name: pulse_core_ios
description: iOS implementation of the pulse_core plugin
version: 1.0.0
homepage: https://pub.dev/

environment:
  sdk: ">=2.19.0 <3.0.0"

flutter:
  plugin:
    implements: pulse_core
    platforms:
      ios:
        pluginClass: PulseCorePlugin
        dartPluginClass: PulseCoreIOS

dependencies:
  flutter:
    sdk: flutter
  pulse_core_platform_interface:
    path: ../pulse_core_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^4.0.0
