name: Publish Plugins

on:
  push:
    tags:
      - 'pulse_core-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v3
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      # Install dependencies
      - name: Install Flutter 🎯
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Configure git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Publish to pub.dev 🚀
        working-directory: pulse_core/pulse_core
        run: flutter pub publish --force
