name: pulse_storage_platform_interface
description: A common platform interface for the pulse_storage plugin.
version: 1.0.0
homepage: https://pub.dev/

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0
