name: pulse_auth
description: Pulse Core Plugin
version: 2.0.0
homepage: https://pub.dev/

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: pulse_auth_android
      ios:
        default_package: pulse_auth_ios
      web:
        default_package: pulse_auth_web

dependencies:
  flutter:
    sdk: flutter
  pulse_auth_android: ^1.0.0
  pulse_auth_ios: ^1.0.0
  pulse_auth_platform_interface: ^1.0.0
  pulse_auth_web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^4.0.0
