name: pulse_core_web
description: Web implementation of the pulse_core plugin
version: 1.0.0
homepage: https://pub.dev/

environment:
  sdk: ">=2.19.0 <3.0.0"

flutter:
  plugin:
    implements: pulse_core
    platforms:
      web:
        pluginClass: PulseCoreWeb
        fileName: pulse_core_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  pulse_core_platform_interface:
    path: ../pulse_core_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0
