name: Publish to pub.dev

on:
  push:
    tags:
      - 'pulse_auth-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: pulse_auth/pulse_auth
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Publish
        run: dart pub publish --force
