name: Publish to pub.dev

on:
  push:
    tags:
      - 'pulse_auth-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - with:
          working-directory: pulse_auth/pulse_auth
      - name: Install dependencies
        run: flutter pub get
      - name: Publish
        run: flutter pub publish --force
