name: Publish Plugins
on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
    with:
      environment: pub.dev
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v3
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Install Flutter 🎯
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Configure git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Git Create Tag
        run: git tag pulse_core-v3.0.0
      - name: Git Push Tags
        run: git push origin --tags
      - name: Activate Melos
        run: dart pub global activate melos
      - name: Publish to pub.dev 🚀
        working-directory: pulse_core/pulse_core
        run: flutter pub publish --force
