name: Verify Pull Request
on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - master
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
    branches: [ "development", "master" ]
jobs:
  verify:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Melos
        run: dart pub global activate melos
      - name: Melos Bootstrap
        run:  melos bootstrap
      - name: Install dependencies
        run: melos get
      - name: Analyze
        run: melos analyze
      - name: Flutter build APK
        run: flutter build apk
      - name: Run Ktlint
        run: (cd example/android &&./gradlew ktlintcheck)
      - name: Run tests
        run:  melos unittest
      - name: Check Publish Warnings
        run: melos exec -c 1 --no-private --ignore="*example*" -- flutter pub publish --dry-run