name: pulse_core
description: Pulse Core Plugin
version: 1.0.0
homepage: https://pub.dev/

environment:
  sdk: ">=2.19.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: pulse_core_android
      ios:
        default_package: pulse_core_ios
      web:
        default_package: pulse_core_web

dependencies:
  flutter:
    sdk: flutter
  pulse_core_android:
  pulse_core_ios:
  pulse_core_platform_interface:
  pulse_core_web:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^4.0.0
